name: SSH Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.temp123 }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 20222 -H ilianko.com >> ~/.ssh/known_hosts

      - name: Deploy to Remote Server
        run: scp -P 20222 -i ~/.ssh/id_rsa index.html ilianko@ilianko.com:~/
